### PR TITLE
Removes deprecation warnings.

### PR DESCRIPTION
**Pull request by nicolasbrugneaux**
:)

### CODE REVIEW

**Comment by kevva** [comment]
Are these stable?

**Comment by nicolasbrugneaux** [comment]
I don't know?
https://atom.io/docs/api/v0.189.0/Workspace#instance-observeTextEditors for example is present since 0.127, I suppose it's stable?

**Comment by kevva** [comment]
`onDidChangeScrollTop` doesn't even exist in the API docs though?

**Comment by nicolasbrugneaux** [comment]
https://github.com/atom/atom/blob/master/src/text-editor.coffee#L451
https://github.com/atom/atom/commit/d4835e1d8e18d2da042b8aa108ccb0b25d439105
I suppose it was never added to the doc? (0.126)

**Comment by nicolasbrugneaux** [comment]
I could do that PR the atom doc maybe.. :dart:

**Comment by nicolasbrugneaux** [comment]
Thanks! :)

**Comment by kevva** [comment]
Thank you :).

**Comment by sindresorhus** [comment]
@nicolasbrugneaux Thank you :)

I saw two more deprecation in Atom 0.190.0 if anyone wants to take a stab at it:

```
Use TextBuffer::onDidSave instead. A TextBuffer instance is no longer provided as a callback argument.
Called 2 timesCreate Issue on jshint repo
TextBuffer.on - /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1182:16
Object.subscribeWith - /Users/sindresorhus/dev/atom-jshint/node_modules/emissary/lib/subscriber.js:28:32
```

```
Use ::addLeftTile({item, priority}) instead.
Called 1 timeCreate Issue on jshint repo
status-bar.appendLeft - /Applications/Atom.app/Contents/Resources/app/node_modules/status-bar/lib/status-bar-view.js:110:12
updateStatusbar - /Users/sindresorhus/dev/atom-jshint/index.js:109:12
```

**Pull request merged**
