### PR TITLE
display missing tooltips on hover

### PR DESCRIPTION
**Pull request by ghost**
Issue #121

### CODE REVIEW

**Comment by thisninja** [comment]
Haven't found how to prevent build failed.

**Comment by sindresorhus** [comment]
Look at the travis output: https://travis-ci.org/sindresorhus/atom-jshint/builds/81857827

It's about code style.

**Comment by Charlie-Y** [comment]
Use
````ES6
const target = editorElement.shadowRoot.querySelectorAll(`.line-number[data-buffer-row="${row}"]`);
```

instead of 

```ES6
const target = editorElement.shadowRoot.querySelectorAll('.line-number[data-buffer-row="' + row + '"]');
```

**Comment by helloncanella** [comment]
Even the topic closed, I didn't understand how to solve the problem.

**Comment by helloncanella** [comment]
Problem solved with the update to the 1.8.3 version

**Pull request closed without merging**
