### PR TITLE
add go-to-next-error command

### LINKED ISSUE #113: `Go To Next Error` command
https://github.com/sindresorhus/atom-jshint/pull/111 implemented a `Go To Error` command. I think it would be useful to have a command to go to the next error. When it hits the end it should just start from the top again.

### PR DESCRIPTION
**Pull request by jacekkopecky**
Well done, your generosity made me do it. :smile:
As before, any comments and suggestions welcome – I've been in coffeescript-land for a while so I'm not sure my javascript is quite clean.
Fixes #113.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Hah, awesome!

I tried it on the `index.js` file in this repo which uses ES2015, so lots of errors because of that. When I'm on line 1 in that file and run "Go to next error", it jumps to line 11 instead of the next error which is on line 3. This can be reproduced with jumping from any error to another, it always skips some.

**Comment by jacekkopecky** [comment]
Ah, guessing (afk atm) that because _.keys returns strings, 11 is sorted
before 3. I'l fix it later today. Sorry about that, should have caught it.

**Comment by jacekkopecky** [comment]
Done, and yup, guessed right.

**Comment by sindresorhus** [comment]
Excellent. Thanks again :beers:

**Comment by jacekkopecky** [comment]
Cheers!

**Pull request closed without merging**
